'use client'
import { useState, useEffect, useRef } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import SiteNav from '@/app/components/SiteNav'

const cycleWords = {
  en: ['rejected.', 'disapproved.', 'flagged.', 'too large.', 'low quality.'],
  pt: ['rejeitados.', 'reprovados.', 'bloqueados.', 'grandes demais.', 'com má qualidade.'],
  es: ['rechazados.', 'desaprobados.', 'bloqueados.', 'demasiado grandes.', 'de mala calidad.'],
}

const t = {
  en: {
    nav_features: 'Features', nav_pricing: 'Pricing', nav_cta: 'Get started', nav_dashboard: 'Dashboard',
    badge: 'No account needed to try',
    hero1: 'Your ads keep getting', hero2: 'rejected.',
    hero3: "We fix that.",
    subtitle: 'Strip metadata, resize to every ad format, and clean your creatives automatically. One click. Works on Meta, Google, TikTok and more.',
    drop: 'Drop images here', drop_sub: 'PNG, JPG, WEBP · Up to 50MB each',
    select: 'Choose files', process: 'Process & Download', processing: 'Processing...',
    clear: 'Clear', success: 'images processed successfully',
    f1_title: 'Metadata stripped', f1_desc: 'Every hidden data point removed before your image reaches any ad platform.', f1_sub: 'EXIF · GPS · Device info · Timestamps',
    f2_title: 'Every ad format', f2_desc: 'Auto-resized to every placement across Meta, Google, TikTok and more.', f2_sub: '1:1 · 4:5 · 9:16 · 1.91:1 · 16:9',
    f3_title: 'Bulk processing', f3_desc: 'Drop 50 images, get 50 clean images back. All at once.', f3_sub: 'Up to 50MB per file · Batch download',
    f4_title: 'AI Autocrop', f4_desc: 'Smart cropping that detects the most important subject in your image and keeps it centered in every format.', f4_sub: 'Content-aware · Zero manual adjustments',
    know_more: 'Learn more →',
    stats: 'No files stored · Processed in memory · Deleted after download',
    free: 'Free', free_sub: 'Get started', free_desc: '10 images per day',
    pro: 'Pro', pro_sub: 'Most popular', pro_desc: 'Unlimited images · All formats · Priority processing',
    platforms: 'Works with',
    choose_platform: 'Choose your platform',
    formats_label: 'Formats generated',
    tiktok_note: 'auto-compressed → 500KB',
    gate_title: 'Your images are ready to be cleaned',
    gate_sub: 'Free plan includes 10 images per day',
    gate_signup: 'Create free account',
    gate_signin: 'Log in',
    gate_b1: 'Platform-specific ad formats',
    gate_b2: 'Metadata stripped automatically',
    gate_b3: 'Bulk processing up to 50 files',
    gate_b4: 'Dashboard with conversion history',
    ai_section_label: 'Coming soon',
    ai_section_title: 'AI-powered tools',
    ai_section_sub: 'The next level of creative automation — coming in our upcoming tier above Pro.',
    ai_outpaint_title: 'AI Outpainting',
    ai_outpaint_desc: 'Instead of cropping when resizing to a new format, AI expands the background to fill the frame. Your product stays intact — no content lost.',
    ai_outpaint_tag: 'No more cropped products · Background generated by AI',
    ai_copy_title: 'Automatic Ad Copy',
    ai_copy_desc: 'AI reads your image and generates platform-optimised ad copy. Meta, Google, TikTok — each with the right tone, format, and character limits.',
    ai_copy_tag: 'Meta · Google · TikTok · Snapchat',
    ai_waitlist_cta: 'Join the waitlist',
    ai_waitlist_note: 'Be the first to know when it launches.',
    ai_plan: 'AI Studio', ai_plan_sub: 'Coming soon', ai_plan_desc: 'Everything in Pro · AI Outpainting · Auto Ad Copy',
    mode_ad: 'Ad formats', mode_clean: 'Metadata only',
    clean_drop: 'Drop any files here', clean_drop_sub: 'Images · PDFs · Any format',
    clean_select: 'Choose files', clean_process: 'Strip & Download', clean_processing: 'Stripping...',
    clean_desc: 'Strip metadata from any file — images, PDFs and more. No resizing.',
    clean_success: (n) => `${n} file${n === 1 ? '' : 's'} cleaned`,
  },
  pt: {
    nav_features: 'Funcionalidades', nav_pricing: 'Preços', nav_cta: 'Começar', nav_dashboard: 'Dashboard',
    badge: 'Sem conta necessária para experimentar',
    hero1: 'Os teus anúncios continuam a ser', hero2: 'rejeitados.',
    hero3: 'Nós resolvemos isso.',
    subtitle: 'Remove metadata, redimensiona para todos os formatos e limpa os teus criativos automaticamente. Um clique. Funciona no Meta, Google, TikTok e mais.',
    drop: 'Arrasta imagens aqui', drop_sub: 'PNG, JPG, WEBP · Até 50MB cada',
    select: 'Escolher ficheiros', process: 'Processar e Descarregar', processing: 'A processar...',
    clear: 'Limpar', success: 'imagens processadas com sucesso',
    f1_title: 'Metadata removida', f1_desc: 'Todos os dados ocultos eliminados antes de a tua imagem chegar a qualquer plataforma.', f1_sub: 'EXIF · GPS · Info do dispositivo · Timestamps',
    f2_title: 'Todos os formatos de anúncio', f2_desc: 'Redimensionado automaticamente para todos os placements do Meta, Google, TikTok e mais.', f2_sub: '1:1 · 4:5 · 9:16 · 1.91:1 · 16:9',
    f3_title: 'Processamento em massa', f3_desc: 'Arrasta 50 imagens, recebe 50 imagens limpas. Tudo de uma vez.', f3_sub: 'Até 50MB por ficheiro · Download em batch',
    f4_title: 'AI Autocrop', f4_desc: 'Corte inteligente que deteta o sujeito mais importante da imagem e mantém-no centrado em todos os formatos.', f4_sub: 'Content-aware · Sem ajustes manuais',
    know_more: 'Saber mais →',
    stats: 'Sem ficheiros guardados · Processado em memória · Eliminado após download',
    free: 'Grátis', free_sub: 'Começar', free_desc: '10 imagens por dia',
    pro: 'Pro', pro_sub: 'Mais popular', pro_desc: 'Imagens ilimitadas · Todos os formatos · Processamento prioritário',
    platforms: 'Funciona com',
    choose_platform: 'Escolhe a tua plataforma',
    formats_label: 'Formatos gerados',
    tiktok_note: 'comprimido automaticamente → 500KB',
    gate_title: 'As tuas imagens estão prontas para serem limpas',
    gate_sub: 'O plano gratuito inclui 10 imagens por dia',
    gate_signup: 'Criar conta gratuita',
    gate_signin: 'Entrar',
    gate_b1: 'Formatos de anúncio por plataforma',
    gate_b2: 'Metadata removida automaticamente',
    gate_b3: 'Processamento em massa até 50 ficheiros',
    gate_b4: 'Dashboard com histórico de conversões',
    ai_section_label: 'Em breve',
    ai_section_title: 'Ferramentas com IA',
    ai_section_sub: 'O próximo nível de automação criativa — disponível em breve no nosso novo plano acima do Pro.',
    ai_outpaint_title: 'AI Outpainting',
    ai_outpaint_desc: 'Em vez de cortar ao redimensionar para um novo formato, a IA expande o fundo para preencher o espaço. O teu produto fica intacto — sem conteúdo perdido.',
    ai_outpaint_tag: 'Sem cortes no produto · Fundo gerado por IA',
    ai_copy_title: 'Copy de Anúncio Automático',
    ai_copy_desc: 'A IA lê a tua imagem e gera copy otimizado para cada plataforma. Meta, Google, TikTok — com o tom certo, formato e limites de caracteres.',
    ai_copy_tag: 'Meta · Google · TikTok · Snapchat',
    ai_waitlist_cta: 'Entrar na lista de espera',
    ai_waitlist_note: 'Sê o primeiro a saber quando lançar.',
    ai_plan: 'AI Studio', ai_plan_sub: 'Em breve', ai_plan_desc: 'Tudo do Pro · AI Outpainting · Copy Automático',
    mode_ad: 'Formatos de anúncio', mode_clean: 'Apenas metadados',
    clean_drop: 'Arrasta qualquer ficheiro', clean_drop_sub: 'Imagens · PDFs · Qualquer formato',
    clean_select: 'Escolher ficheiros', clean_process: 'Limpar e Descarregar', clean_processing: 'A limpar...',
    clean_desc: 'Remove metadados de qualquer ficheiro — imagens, PDFs e mais. Sem redimensionar.',
    clean_success: (n) => `${n} ficheiro${n === 1 ? '' : 's'} limpo${n === 1 ? '' : 's'}`,
  },
  es: {
    nav_features: 'Funciones', nav_pricing: 'Precios', nav_cta: 'Empezar', nav_dashboard: 'Dashboard',
    badge: 'Sin cuenta necesaria para probar',
    hero1: 'Tus anuncios siguen siendo', hero2: 'rechazados.',
    hero3: 'Nosotros lo solucionamos.',
    subtitle: 'Elimina metadatos, redimensiona a todos los formatos y limpia tus creativos automáticamente. Un clic. Funciona en Meta, Google, TikTok y más.',
    drop: 'Arrastra imágenes aquí', drop_sub: 'PNG, JPG, WEBP · Hasta 50MB cada una',
    select: 'Elegir archivos', process: 'Procesar y Descargar', processing: 'Procesando...',
    clear: 'Limpiar', success: 'imágenes procesadas correctamente',
    f1_title: 'Metadatos eliminados', f1_desc: 'Todos los datos ocultos eliminados antes de que tu imagen llegue a cualquier plataforma.', f1_sub: 'EXIF · GPS · Info del dispositivo · Timestamps',
    f2_title: 'Todos los formatos de anuncio', f2_desc: 'Redimensionado automáticamente para todos los placements de Meta, Google, TikTok y más.', f2_sub: '1:1 · 4:5 · 9:16 · 1.91:1 · 16:9',
    f3_title: 'Procesamiento masivo', f3_desc: 'Sube 50 imágenes, recibe 50 imágenes limpias. Todo a la vez.', f3_sub: 'Hasta 50MB por archivo · Descarga en batch',
    f4_title: 'AI Autocrop', f4_desc: 'Recorte inteligente que detecta el sujeto más importante de tu imagen y lo mantiene centrado en cada formato.', f4_sub: 'Content-aware · Sin ajustes manuales',
    know_more: 'Saber más →',
    stats: 'Sin archivos guardados · Procesado en memoria · Eliminado tras la descarga',
    free: 'Gratis', free_sub: 'Empezar', free_desc: '10 imágenes por día',
    pro: 'Pro', pro_sub: 'Más popular', pro_desc: 'Imágenes ilimitadas · Todos los formatos · Procesamiento prioritario',
    platforms: 'Funciona con',
    choose_platform: 'Elige tu plataforma',
    formats_label: 'Formatos generados',
    tiktok_note: 'comprimido automáticamente → 500KB',
    gate_title: 'Tus imágenes están listas para limpiar',
    gate_sub: 'El plan gratuito incluye 10 imágenes por día',
    gate_signup: 'Crear cuenta gratis',
    gate_signin: 'Iniciar sesión', /* log in */
    gate_b1: 'Formatos de anuncio por plataforma',
    gate_b2: 'Metadatos eliminados automáticamente',
    gate_b3: 'Procesamiento masivo hasta 50 archivos',
    gate_b4: 'Dashboard con historial de conversiones',
    ai_section_label: 'Próximamente',
    ai_section_title: 'Herramientas con IA',
    ai_section_sub: 'El siguiente nivel de automatización creativa — disponible próximamente en nuestro nuevo plan por encima de Pro.',
    ai_outpaint_title: 'AI Outpainting',
    ai_outpaint_desc: 'En lugar de recortar al cambiar de formato, la IA expande el fondo para llenar el marco. Tu producto queda intacto — sin perder contenido.',
    ai_outpaint_tag: 'Sin recortes en el producto · Fondo generado por IA',
    ai_copy_title: 'Copy de Anuncio Automático',
    ai_copy_desc: 'La IA analiza tu imagen y genera copy optimizado para cada plataforma. Meta, Google, TikTok — con el tono, formato y límites de caracteres correctos.',
    ai_copy_tag: 'Meta · Google · TikTok · Snapchat',
    ai_waitlist_cta: 'Unirse a la lista de espera',
    ai_waitlist_note: 'Sé el primero en saber cuándo lanza.',
    ai_plan: 'AI Studio', ai_plan_sub: 'Próximamente', ai_plan_desc: 'Todo lo de Pro · AI Outpainting · Copy Automático',
    mode_ad: 'Formatos de anuncio', mode_clean: 'Solo metadatos',
    clean_drop: 'Arrastra cualquier archivo', clean_drop_sub: 'Imágenes · PDFs · Cualquier formato',
    clean_select: 'Elegir archivos', clean_process: 'Limpiar y Descargar', clean_processing: 'Limpiando...',
    clean_desc: 'Elimina metadatos de cualquier archivo — imágenes, PDFs y más. Sin redimensionar.',
    clean_success: (n) => `${n} archivo${n === 1 ? '' : 's'} limpiado${n === 1 ? '' : 's'}`,
  },
}


const glowStyle = {
  background: 'linear-gradient(135deg, #2563eb, #4f46e5, #8b5cf6, #6366f1)',
  backgroundSize: '300% 300%',
  backgroundPosition: '0% 50%',
  transition: 'box-shadow 0.4s ease, background-position 0.1s ease',
}

const glowHandlers = {
  onMouseEnter: (e) => {
    e.currentTarget.style.backgroundPosition = '100% 50%'
    e.currentTarget.style.boxShadow = '0 0 0 1px rgba(139,92,246,0.6), 0 0 20px rgba(99,102,241,0.5), 0 0 45px rgba(139,92,246,0.25)'
    e.currentTarget.style.transform = 'scale(1.02)'
  },
  onMouseLeave: (e) => {
    e.currentTarget.style.backgroundPosition = '0% 50%'
    e.currentTarget.style.boxShadow = 'none'
    e.currentTarget.style.transform = 'scale(1)'
  },
  onMouseMove: (e) => {
    const rect = e.currentTarget.getBoundingClientRect()
    const x = ((e.clientX - rect.left) / rect.width * 100).toFixed(1)
    e.currentTarget.style.backgroundPosition = `${x}% 50%`
  },
}

function Reveal({ children, delay = 0, y = 20, className = '', style: extStyle = {} }) {
  const ref = useRef(null)
  const [visible, setVisible] = useState(false)
  useEffect(() => {
    const el = ref.current
    if (!el) return
    const obs = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) { setVisible(true); obs.disconnect() } },
      { threshold: 0.05, rootMargin: '0px 0px -30px 0px' }
    )
    obs.observe(el)
    return () => obs.disconnect()
  }, [])
  return (
    <div
      ref={ref}
      className={className}
      style={{
        opacity: visible ? 1 : 0,
        transform: visible ? 'none' : `translateY(${y}px)`,
        transition: `opacity 0.6s cubic-bezier(0.16,1,0.3,1) ${delay}ms, transform 0.6s cubic-bezier(0.16,1,0.3,1) ${delay}ms`,
        ...extStyle,
      }}
    >
      {children}
    </div>
  )
}

function IconUpload() {
  return <svg className="w-8 h-8 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.2} d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5" /></svg>
}

function IconFile() {
  return <svg className="w-3.5 h-3.5 text-blue-400 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" /></svg>
}

function IconDownload() {
  return <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" /></svg>
}

function IconCheck() {
  return <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4.5 12.75l6 6 9-13.5" /></svg>
}

function IconSpin() {
  return <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z"/></svg>
}

function IconShield() {
  return <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" /></svg>
}

function IconResize() {
  return <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3.75 3.75v4.5m0-4.5h4.5m-4.5 0L9 9M3.75 20.25v-4.5m0 4.5h4.5m-4.5 0L9 15M20.25 3.75h-4.5m4.5 0v4.5m0-4.5L15 9m5.25 11.25h-4.5m4.5 0v-4.5m0 4.5L15 15" /></svg>
}

function IconBolt() {
  return <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z" /></svg>
}

function IconAIExpand() {
  return <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3.75 3.75v4.5m0-4.5h4.5m-4.5 0L9 9M3.75 20.25v-4.5m0 4.5h4.5m-4.5 0L9 15M20.25 3.75h-4.5m4.5 0v4.5m0-4.5L15 9m5.25 11.25h-4.5m4.5 0v-4.5m0 4.5L15 15" /></svg>
}

function IconAIText() {
  return <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 01.865-.501 48.172 48.172 0 003.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" /></svg>
}

function PlatformIcon({ platform }) {
  const s = { width: 15, height: 15, style: { display: 'block', flexShrink: 0 } }
  if (platform === 'meta') return (
    <svg {...s} viewBox="0 0 24 24" fill="none">
      <path d="M12 9.5c-1.5-2.2-3.2-3.5-5-3.5C4.1 6 2 8.2 2 11c0 1.8.9 3.3 2.3 4.2.9.6 1.8.8 2.7.8 1.8 0 3.5-1.4 5-3.5 1.5 2.1 3.2 3.5 5 3.5.9 0 1.8-.2 2.7-.8C21.1 14.3 22 12.8 22 11c0-2.8-2.1-5-5-5-1.8 0-3.5 1.3-5 3.5z" fill="#1877f2"/>
    </svg>
  )
  if (platform === 'google') return (
    <svg {...s} viewBox="0 0 24 24">
      <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"/>
      <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"/>
      <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l3.66-2.84z" fill="#FBBC05"/>
      <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"/>
    </svg>
  )
  if (platform === 'tiktok') return (
    <svg {...s} viewBox="0 0 24 24">
      <path d="M19.59 6.69a4.83 4.83 0 01-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 01-2.88 2.5 2.89 2.89 0 01-2.89-2.89 2.89 2.89 0 012.89-2.89c.28 0 .54.04.79.1V9.01a6.32 6.32 0 00-.79-.05 6.34 6.34 0 00-6.34 6.34 6.34 6.34 0 006.34 6.34 6.34 6.34 0 006.33-6.34V8.69a8.18 8.18 0 004.78 1.52V6.78a4.85 4.85 0 01-1.01-.09z" fill="#ff0050"/>
    </svg>
  )
  if (platform === 'snapchat') return (
    <svg {...s} viewBox="0 0 24 24">
      <path d="M12.206.793c.99 0 4.347.276 5.93 3.821.529 1.193.403 3.219.317 4.814l-.004.061c-.004.071-.007.141-.01.211.129.06.264.107.4.117a1.104 1.104 0 00.606-.182c.083-.049.156-.063.225-.063.284 0 .573.211.573.508 0 .395-.3.544-.587.665-.064.028-.134.055-.194.085-.48.247-.646.607-.542.905.262.748 1.177 1.21 1.853 1.482l.06.025c.327.13.614.243.8.38.42.306.634.742.627 1.25-.011.664-.423 1.046-.798 1.046-.153 0-.289-.048-.43-.095-.327-.11-.651-.222-.984-.222-.228 0-.443.044-.645.137-.29.133-.516.308-.734.477-.518.403-1.094.851-2.257.851-.062 0-.127-.003-.194-.009-.527-.049-1.006-.195-1.42-.336-.398-.137-.771-.266-1.141-.266-.37 0-.743.129-1.141.266-.414.141-.893.287-1.42.336-.067.006-.132.009-.194.009-1.163 0-1.739-.448-2.257-.851-.218-.169-.444-.344-.734-.477-.202-.093-.417-.137-.645-.137-.333 0-.657.112-.984.222-.141.047-.277.095-.43.095-.375 0-.787-.382-.798-1.046-.007-.508.207-.944.627-1.25.186-.137.473-.25.8-.38l.06-.025c.676-.272 1.591-.734 1.853-1.482.104-.298-.062-.658-.542-.905-.06-.03-.13-.057-.194-.085-.287-.121-.587-.27-.587-.665 0-.297.289-.508.573-.508.069 0 .142.014.225.063a1.1 1.1 0 00.606.182c.136-.01.271-.057.4-.117l-.01-.211-.004-.061c-.086-1.595-.212-3.621.317-4.814C7.859 1.069 11.216.793 12.206.793z" fill="#fffc00"/>
    </svg>
  )
  if (platform === 'pinterest') return (
    <svg {...s} viewBox="0 0 24 24" fill="#e60023">
      <path d="M12 0C5.373 0 0 5.373 0 12c0 5.084 3.163 9.426 7.627 11.174-.105-.949-.2-2.405.042-3.441.218-.937 1.407-5.965 1.407-5.965s-.359-.719-.359-1.782c0-1.668.967-2.914 2.171-2.914 1.023 0 1.518.769 1.518 1.69 0 1.029-.655 2.568-.994 3.995-.283 1.194.599 2.169 1.777 2.169 2.133 0 3.772-2.249 3.772-5.495 0-2.873-2.064-4.882-5.012-4.882-3.414 0-5.418 2.561-5.418 5.207 0 1.031.397 2.138.893 2.738a.36.36 0 01.083.345l-.333 1.36c-.053.22-.174.267-.402.161-1.499-.698-2.436-2.889-2.436-4.649 0-3.785 2.75-7.262 7.929-7.262 4.163 0 7.398 2.967 7.398 6.931 0 4.136-2.607 7.464-6.227 7.464-1.216 0-2.359-.632-2.75-1.378l-.748 2.853c-.271 1.043-1.002 2.35-1.492 3.146C9.57 23.812 10.763 24 12 24c6.627 0 12-5.373 12-12S18.627 0 12 0z"/>
    </svg>
  )
  if (platform === 'linkedin') return (
    <svg {...s} viewBox="0 0 24 24" fill="#0a66c2">
      <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
    </svg>
  )
  return <div style={{width:15,height:15,borderRadius:'50%',background:'#6366f1',flexShrink:0}} />
}

function Logo() {
  return (
    <div style={{display:'flex', alignItems:'center', gap:'10px'}}>
      <svg width="30" height="30" viewBox="0 0 56 56" fill="none">
        <defs>
          <clipPath id="iconClip">
            <rect width="56" height="56" rx="13"/>
          </clipPath>
        </defs>
        <rect width="56" height="56" rx="13" fill="#4338ca"/>
        <g clipPath="url(#iconClip)">
          <circle cx="14" cy="18" r="5" fill="rgba(255,255,255,0.9)"/>
          <polygon points="6,52 22,26 38,52" fill="rgba(255,255,255,0.9)"/>
          <polygon points="24,52 36,34 50,52" fill="rgba(255,255,255,0.7)"/>
          <polygon points="34,0 56,0 56,24" fill="#060609"/>
          <line x1="34" y1="0" x2="56" y2="24" stroke="#a5b4fc" strokeWidth="2" strokeLinecap="round"/>
        </g>
      </svg>
      <span style={{fontFamily:'-apple-system,BlinkMacSystemFont,"Helvetica Neue",sans-serif', fontSize:'19px', letterSpacing:'-0.7px', lineHeight:1}}>
        <span style={{fontWeight:800, color:'white'}}>meta</span>
        <span style={{fontWeight:200, color:'rgba(255,255,255,0.45)'}}>clean</span>
      </span>
    </div>
  )
}

const PLATFORM_CONFIGS = {
  meta:      { name: 'Meta Ads',   color: '#1877f2', formats: ['1:1 · 1080×1080', '4:5 · 1080×1350', '9:16 · 1080×1920', '1.91:1 · 1200×628'] },
  google:    { name: 'Google Ads', color: '#4285f4', formats: ['1.91:1 · 1200×628', '1:1 · 1200×1200', '4:5 · 1200×1500'] },
  tiktok:    { name: 'TikTok Ads', color: '#ff0050', formats: ['9:16 · 1080×1920', '1:1 · 1080×1080'] },
  snapchat:  { name: 'Snapchat',   color: '#fffc00', formats: ['9:16 · 1080×1920'] },
  pinterest: { name: 'Pinterest',  color: '#e60023', formats: ['2:3 · 1000×1500', '1:1 · 1000×1000'] },
  linkedin:  { name: 'LinkedIn',   color: '#0a66c2', formats: ['1.91:1 · 1200×628', '1:1 · 1200×1200'] },
}

function AuthGateModal({ onClose, lang }) {
  const i = t[lang]
  const router = useRouter()
  const benefits = [i.gate_b1, i.gate_b2, i.gate_b3, i.gate_b4]

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center px-4"
      style={{background: 'rgba(6,6,9,0.85)', backdropFilter: 'blur(12px)'}}
      onClick={(e) => { if (e.target === e.currentTarget) onClose() }}
    >
      <div
        className="w-full max-w-md rounded-2xl p-8"
        style={{
          background: 'linear-gradient(145deg, #0d0d18, #0a0a14)',
          border: '1px solid rgba(99,102,241,0.2)',
          boxShadow: '0 0 60px rgba(99,102,241,0.12), 0 40px 80px rgba(0,0,0,0.5)',
        }}
      >
        {/* Glow line top */}
        <div className="absolute top-0 left-8 right-8 h-px rounded-full" style={{background: 'linear-gradient(90deg, transparent, rgba(99,102,241,0.5), transparent)'}} />

        <div className="text-center mb-7">
          <div className="inline-flex w-12 h-12 rounded-2xl items-center justify-center mb-4" style={{background: 'rgba(99,102,241,0.12)', border: '1px solid rgba(99,102,241,0.2)'}}>
            <svg className="w-5 h-5 text-indigo-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.8} d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
          </div>
          <h2 className="text-xl font-bold tracking-tight mb-2">{i.gate_title}</h2>
        </div>

        <ul className="space-y-2.5 mb-7">
          {benefits.map((b, idx) => (
            <li key={idx} className="flex items-center gap-3 text-[13px] text-gray-300">
              <div className="w-4 h-4 rounded-full flex items-center justify-center shrink-0" style={{background: 'rgba(99,102,241,0.15)', border: '1px solid rgba(99,102,241,0.3)'}}>
                <svg className="w-2.5 h-2.5 text-indigo-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M4.5 12.75l6 6 9-13.5" /></svg>
              </div>
              {b}
            </li>
          ))}
        </ul>

        <div className="space-y-2.5">
          <button
            {...glowHandlers}
            onClick={() => router.push('/login?mode=signup')}
            className="w-full py-3 rounded-xl text-[13px] font-semibold text-white"
            style={glowStyle}
          >
            {i.gate_signup}
          </button>
          <button
            onClick={() => router.push('/login')}
            className="w-full py-3 rounded-xl text-[13px] font-medium text-gray-300 hover:text-white transition-colors"
            style={{border: '1px solid rgba(255,255,255,0.08)'}}
          >
            {i.gate_signin}
          </button>
        </div>

        <p className="text-center text-[11px] text-gray-600 mt-4">{i.gate_sub}</p>
      </div>
    </div>
  )
}

export default function Home() {
  const router = useRouter()
  const [files, setFiles] = useState([])
  const [processing, setProcessing] = useState(false)
  const [done, setDone] = useState(false)
  const [dragging, setDragging] = useState(false)
  const [lang, setLang] = useState('en')
  const [wordIdx, setWordIdx] = useState(0)
  const [wordVisible, setWordVisible] = useState(true)
  const [selectedPlatform, setSelectedPlatform] = useState('meta')
  const [session, setSession] = useState(null)
  const [showGate, setShowGate] = useState(false)
  const fileInputRef = useRef(null)
  const homeMode = 'ad'
  const [cleanFiles, setCleanFiles] = useState([])
  const [cleanDragging, setCleanDragging] = useState(false)
  const [cleanProcessing, setCleanProcessing] = useState(false)
  const [cleanDone, setCleanDone] = useState(false)
  const cleanFileInputRef = useRef(null)

  const i = t[lang]

  useEffect(() => {
    const words = cycleWords[lang]
    const cycle = setInterval(() => {
      setWordVisible(false)
      setTimeout(() => {
        setWordIdx(idx => (idx + 1) % words.length)
        setWordVisible(true)
      }, 300)
    }, 2800)
    return () => clearInterval(cycle)
  }, [lang])

  useEffect(() => {
    const saved = localStorage.getItem('metaclean_lang')
    if (saved && ['en', 'pt', 'es'].includes(saved)) setLang(saved)

    const onLang = (e) => setLang(e.detail)
    window.addEventListener('metaclean:lang', onLang)

    if (new URLSearchParams(window.location.search).get('error')) {
      window.history.replaceState({}, '', window.location.pathname)
    }

    supabase.auth.getSession().then(({ data }) => {
      if (data.session) { router.replace('/dashboard'); return }
      setSession(data.session)
    })
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_, s) => {
      if (s) { router.replace('/dashboard'); return }
      setSession(s)
    })
    return () => {
      subscription.unsubscribe()
      window.removeEventListener('metaclean:lang', onLang)
    }
  }, [router])

  const storeFilesForAfterAuth = (filesToStore) => {
    try {
      const images = filesToStore.filter(f => f.type.startsWith('image/'))
      if (images.length === 0) return
      let totalSize = images.reduce((s, f) => s + f.size, 0)
      if (totalSize > 4 * 1024 * 1024) return // skip if > 4MB total (sessionStorage limit)
      Promise.all(images.map(f => new Promise((res) => {
        const reader = new FileReader()
        reader.onload = () => res({ name: f.name, type: f.type, data: reader.result })
        reader.onerror = () => res(null)
        reader.readAsDataURL(f)
      }))).then(results => {
        const valid = results.filter(Boolean)
        if (valid.length > 0) sessionStorage.setItem('metaclean_pending', JSON.stringify(valid))
      })
    } catch {}
  }

  const interceptFiles = (incomingFiles, mode = 'ad') => {
    storeFilesForAfterAuth(incomingFiles)
    router.push(`/dashboard?mode=${mode}`)
  }

  const handleFiles = (e) => interceptFiles(Array.from(e.target.files))
  const handleDrop = (e) => {
    e.preventDefault()
    setDragging(false)
    interceptFiles(Array.from(e.dataTransfer.files))
  }

  const processImages = async () => {
    if (!session) { storeFilesForAfterAuth(files); router.push('/dashboard?mode=ad'); return }
    setProcessing(true)
    try {
      const { data } = await supabase.auth.getSession()
      const token = data.session?.access_token
      const fileSnapshots = await Promise.all(files.map(async (file) => ({ blob: new Blob([await file.arrayBuffer()], { type: file.type }), name: file.name })))
      let downloaded = 0
      for (const { blob, name } of fileSnapshots) {
        const formData = new FormData()
        formData.append('image', blob, name)
        formData.append('platform', selectedPlatform)
        formData.append('name', name)
        const res = await fetch('/api/process', { method: 'POST', headers: { 'Authorization': `Bearer ${token}` }, body: formData })
        if (!res.ok) continue
        const resBlob = await res.blob()
        const url = URL.createObjectURL(resBlob)
        const a = document.createElement('a')
        a.href = url; a.download = `metaclean_${name.replace(/\.[^.]+$/, '')}_${selectedPlatform}.zip`
        document.body.appendChild(a); a.click(); document.body.removeChild(a)
        setTimeout(() => URL.revokeObjectURL(url), 1000)
        downloaded++
      }
      if (downloaded > 0) setDone(true)
    } catch (err) { console.error('processImages error:', err) }
    finally { setProcessing(false) }
  }

  const processCleanHome = async () => {
    if (!session) { storeFilesForAfterAuth(cleanFiles); router.push('/dashboard?mode=clean'); return }
    setCleanProcessing(true)
    try {
      const { data } = await supabase.auth.getSession()
      const token = data.session?.access_token
      // Read all files into memory first so deleting them from disk mid-process doesn't hang
      const cleanSnapshots = await Promise.all(
        cleanFiles.map(async (file) => ({
          blob: new Blob([await file.arrayBuffer()], { type: file.type }),
          name: file.name,
        }))
      )
      const results = []
      for (const { blob: fileBlob, name } of cleanSnapshots) {
        const formData = new FormData()
        formData.append('file', fileBlob, name)
        formData.append('name', name)
        const res = await fetch('/api/clean', { method: 'POST', headers: { 'Authorization': `Bearer ${token}` }, body: formData })
        if (!res.ok) continue
        const resBlob = await res.blob()
        const cd = res.headers.get('Content-Disposition') || ''
        const nameMatch = cd.match(/filename="(.+?)"/)
        results.push({ blob: resBlob, name: nameMatch?.[1] || `clean_${name}` })
      }
      if (results.length === 1) {
        const url = URL.createObjectURL(results[0].blob)
        const a = document.createElement('a')
        a.href = url; a.download = results[0].name
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        setTimeout(() => URL.revokeObjectURL(url), 1000)
        setCleanDone(true)
      } else if (results.length > 1) {
        const JSZip = (await import('jszip')).default
        const zip = new JSZip()
        results.forEach(r => zip.file(r.name, r.blob))
        const zipBlob = await zip.generateAsync({ type: 'blob' })
        const url = URL.createObjectURL(zipBlob)
        const a = document.createElement('a')
        a.href = url; a.download = 'metaclean_cleaned.zip'
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        setTimeout(() => URL.revokeObjectURL(url), 1000)
        setCleanDone(true)
      }
    } catch (err) {
      console.error('processCleanHome error:', err)
    } finally {
      setCleanProcessing(false)
    }
  }

  const features = [
    { Icon: IconShield,   title: i.f1_title, desc: i.f1_desc, sub: i.f1_sub, accent: '#3b82f6', href: '/features#metadata' },
    { Icon: IconResize,   title: i.f2_title, desc: i.f2_desc, sub: i.f2_sub, accent: '#8b5cf6', href: '/features#formats' },
    { Icon: IconBolt,     title: i.f3_title, desc: i.f3_desc, sub: i.f3_sub, accent: '#6366f1', href: '/features#bulk' },
    { Icon: IconAIExpand, title: i.f4_title, desc: i.f4_desc, sub: i.f4_sub, accent: '#8b5cf6', href: '/features#ai-autocrop' },
  ]

  return (
    <main className="min-h-screen bg-[#060609] text-white overflow-x-hidden" style={{fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'}}>

      {showGate && <AuthGateModal onClose={() => setShowGate(false)} lang={lang} />}

      {/* Background glows */}
      <div className="fixed inset-0 pointer-events-none">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[500px]" style={{background: 'radial-gradient(ellipse at top, rgba(59,130,246,0.07) 0%, transparent 65%)'}} />
        <div className="absolute top-1/3 left-1/4 w-[400px] h-[400px] rounded-full" style={{background: 'radial-gradient(circle, rgba(99,102,241,0.04) 0%, transparent 70%)'}} />
      </div>

      <SiteNav />

      <div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 pt-16 sm:pt-28 pb-24 sm:pb-32">

        {/* Hero */}
        <Reveal className="text-center mb-10 sm:mb-16">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full text-[11px] font-medium tracking-wide mb-8 sm:mb-10 uppercase" style={{background: 'rgba(59,130,246,0.08)', border: '1px solid rgba(59,130,246,0.18)', color: '#93bbfd', letterSpacing: '0.08em'}}>
            <span className="w-1.5 h-1.5 rounded-full bg-blue-400 animate-pulse inline-block"></span>
            {i.badge}
          </div>

          <h1 className="font-bold mb-5 sm:mb-6 tracking-tight leading-[1.1]" style={{fontSize: 'clamp(30px, 5vw, 72px)'}}>
            <span className="text-gray-100">{i.hero1}</span><br />
            <span
              style={{
                display: 'inline-block',
                background: 'linear-gradient(135deg, #38bdf8, #6366f1, #e879f9, #38bdf8)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
                backgroundSize: '300% 300%',
                backgroundPosition: '0% 50%',
                paddingBottom: '0.12em',
                opacity: wordVisible ? 1 : 0,
                transform: wordVisible ? 'translateY(0)' : 'translateY(-10px)',
                transition: wordVisible
                  ? 'opacity 0.4s cubic-bezier(0.16,1,0.3,1), transform 0.4s cubic-bezier(0.16,1,0.3,1)'
                  : 'opacity 0.25s ease, transform 0.25s ease',
              }}
            >
              <span style={{textTransform: 'uppercase'}}>{cycleWords[lang][wordIdx].charAt(0)}</span>
              {cycleWords[lang][wordIdx].slice(1)}
            </span>
            <br />
            <span className="text-gray-100">{i.hero3}</span>
          </h1>

          <p className="text-gray-400 max-w-lg mx-auto leading-relaxed mb-8 sm:mb-10 px-2 sm:px-0" style={{fontSize: 'clamp(15px, 2vw, 17px)'}}>{i.subtitle}</p>

          {/* Mode toggle */}
          <div className="flex justify-center mb-8">
            <div className="flex items-center gap-1.5 p-1 rounded-xl" style={{background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.07)', display: 'inline-flex'}}>
              {[['ad', i.mode_ad], ['clean', i.mode_clean]].map(([mode, label]) => (
                <button
                  key={mode}
                  onClick={() => router.push(`/dashboard?mode=${mode}`)}
                  className="px-4 py-1.5 rounded-lg text-[13px] font-medium transition-all duration-200"
                  style={{
                    background: homeMode === mode ? 'rgba(255,255,255,0.08)' : 'transparent',
                    color: homeMode === mode ? 'white' : 'rgba(255,255,255,0.4)',
                    border: homeMode === mode ? '1px solid rgba(255,255,255,0.12)' : '1px solid transparent',
                  }}
                >{label}</button>
              ))}
            </div>
          </div>

          {/* Platform selector — ad mode only */}
          {homeMode === 'ad' && (
          <div>
            <p className="text-[11px] text-gray-500 uppercase tracking-widest mb-4">{i.choose_platform}</p>
            <div className="flex items-center justify-center gap-2 flex-wrap mb-4">
              {Object.entries(PLATFORM_CONFIGS).map(([key, p]) => (
                <button
                  key={key}
                  onClick={() => setSelectedPlatform(key)}
                  onMouseEnter={e => { if (selectedPlatform !== key) { e.currentTarget.style.background = `${p.color}10`; e.currentTarget.style.borderColor = `${p.color}35`; e.currentTarget.style.color = 'rgba(255,255,255,0.75)' } }}
                  onMouseLeave={e => { if (selectedPlatform !== key) { e.currentTarget.style.background = 'rgba(255,255,255,0.03)'; e.currentTarget.style.borderColor = 'rgba(255,255,255,0.07)'; e.currentTarget.style.color = 'rgba(255,255,255,0.45)' } }}
                  className="flex items-center gap-2 px-3 sm:px-4 py-1.5 sm:py-2 rounded-xl text-[12px] sm:text-[13px] font-medium transition-all duration-200"
                  style={{
                    background: selectedPlatform === key ? `${p.color}18` : 'rgba(255,255,255,0.03)',
                    border: selectedPlatform === key ? `1px solid ${p.color}55` : '1px solid rgba(255,255,255,0.07)',
                    color: selectedPlatform === key ? 'white' : 'rgba(255,255,255,0.45)',
                    transform: selectedPlatform === key ? 'scale(1.04)' : 'scale(1)',
                  }}
                >
                  <PlatformIcon platform={key} />
                  {p.name}
                </button>
              ))}
            </div>
            <div className="flex items-center justify-center gap-2 flex-wrap">
              <span className="text-[11px] text-gray-600 uppercase tracking-widest">{i.formats_label}:</span>
              {PLATFORM_CONFIGS[selectedPlatform].formats.map((f, idx) => (
                <span key={idx} className="text-[11px] px-2.5 py-1 rounded-md font-medium" style={{background: 'rgba(99,102,241,0.08)', border: '1px solid rgba(99,102,241,0.18)', color: '#a5b4fc'}}>
                  {f}
                </span>
              ))}
              {selectedPlatform === 'tiktok' && (
                <span className="text-[11px] px-2.5 py-1 rounded-md font-medium" style={{background: 'rgba(255,80,0,0.08)', border: '1px solid rgba(255,80,0,0.25)', color: '#fb923c'}}>
                  {i.tiktok_note}
                </span>
              )}
            </div>
          </div>
          )}

          {/* Clean mode description */}
          {homeMode === 'clean' && (
            <p className="text-[13px] text-gray-500 mb-2">{i.clean_desc}</p>
          )}
        </Reveal>

        {/* Upload zone */}
        <Reveal y={12}>
          {homeMode === 'ad' ? (
          <div
            onClick={() => { if (!session) router.push('/dashboard?mode=ad') }}
            onDrop={handleDrop}
            onDragOver={(e) => { e.preventDefault(); setDragging(true) }}
            onDragLeave={() => setDragging(false)}
            className="rounded-2xl transition-all duration-300 mb-4 px-5 py-10 sm:px-10 sm:py-14"
            style={{
              background: dragging ? 'rgba(59,130,246,0.06)' : 'rgba(255,255,255,0.025)',
              border: dragging ? '1.5px solid rgba(99,102,241,0.5)' : '1.5px dashed rgba(255,255,255,0.08)',
              boxShadow: dragging ? '0 0 0 4px rgba(99,102,241,0.08)' : 'none',
              textAlign: 'center',
            }}
          >
            {files.length === 0 ? (
              <>
                <div className="w-14 h-14 rounded-2xl mx-auto mb-5 flex items-center justify-center" style={{background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.07)'}}>
                  <IconUpload />
                </div>
                <p className="text-white font-semibold text-lg mb-2">{i.drop}</p>
                <p className="text-gray-500 text-sm mb-8">{i.drop_sub}</p>
                <label onClick={(e) => { if (!session) { e.preventDefault(); router.push('/dashboard?mode=ad') } }} {...glowHandlers} className="inline-flex items-center gap-2 px-7 py-3 rounded-xl text-sm font-semibold text-white cursor-pointer" style={glowStyle}>
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" /></svg>
                  {i.select}
                  <input ref={fileInputRef} type="file" multiple accept="image/*" className="hidden" onChange={handleFiles} />
                </label>
              </>
            ) : (
              <>
                <div className="flex flex-wrap gap-2 justify-center mb-8 max-h-36 overflow-y-auto">
                  {files.map((f, idx) => (
                    <div key={idx} className="flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs" style={{background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.07)'}}>
                      <IconFile />
                      <span className="text-gray-300 max-w-[120px] truncate">{f.name}</span>
                      <span className="text-gray-600">{(f.size/1024).toFixed(0)}kb</span>
                    </div>
                  ))}
                </div>
                <div className="flex items-center justify-center gap-3 flex-wrap">
                  <button onClick={processImages} disabled={processing} {...glowHandlers} className="inline-flex items-center gap-2.5 px-7 sm:px-9 py-3.5 rounded-xl text-sm font-semibold text-white disabled:opacity-40" style={glowStyle}>
                    {processing ? <><IconSpin />{i.processing}</> : <><IconDownload />{i.process}</>}
                  </button>
                  <button onClick={() => { setFiles([]); setDone(false) }} className="px-4 py-3.5 text-xs text-gray-500 hover:text-gray-300 transition-colors tracking-wide">{i.clear}</button>
                </div>
                {done && (
                  <div className="mt-6 inline-flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-medium" style={{background: 'rgba(34,197,94,0.08)', border: '1px solid rgba(34,197,94,0.18)', color: '#86efac'}}>
                    <IconCheck />{files.length} {i.success}
                  </div>
                )}
              </>
            )}
          </div>
          ) : (
          <div
            onClick={() => { if (!session) router.push('/dashboard?mode=clean') }}
            onDrop={(e) => { e.preventDefault(); setCleanDragging(false); const f = Array.from(e.dataTransfer.files); if (!session) { storeFilesForAfterAuth(f); router.push('/dashboard?mode=clean'); return }; setCleanFiles(prev => [...prev, ...f]); setCleanDone(false) }}
            onDragOver={(e) => { e.preventDefault(); setCleanDragging(true) }}
            onDragLeave={() => setCleanDragging(false)}
            className="rounded-2xl transition-all duration-300 mb-4 px-5 py-10 sm:px-10 sm:py-14"
            style={{
              background: cleanDragging ? 'rgba(99,102,241,0.06)' : 'rgba(255,255,255,0.025)',
              border: cleanDragging ? '1.5px solid rgba(99,102,241,0.5)' : '1.5px dashed rgba(99,102,241,0.15)',
              boxShadow: cleanDragging ? '0 0 0 4px rgba(99,102,241,0.08)' : 'none',
              textAlign: 'center',
            }}
          >
            {cleanFiles.length === 0 ? (
              <>
                <div className="w-14 h-14 rounded-2xl mx-auto mb-5 flex items-center justify-center" style={{background: 'rgba(99,102,241,0.08)', border: '1px solid rgba(99,102,241,0.15)'}}>
                  <svg className="w-6 h-6" style={{color:'#818cf8'}} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" /></svg>
                </div>
                <p className="text-white font-semibold text-lg mb-2">{i.clean_drop}</p>
                <p className="text-gray-500 text-sm mb-8">{i.clean_drop_sub}</p>
                <label onClick={(e) => { if (!session) { e.preventDefault(); router.push('/dashboard?mode=clean') } }} className="inline-flex items-center gap-2 px-7 py-3 rounded-xl text-sm font-semibold cursor-pointer transition-all duration-200" style={{background: 'rgba(99,102,241,0.12)', border: '1px solid rgba(99,102,241,0.3)', color: '#a5b4fc'}}
                  onMouseEnter={e => e.currentTarget.style.background = 'rgba(99,102,241,0.2)'}
                  onMouseLeave={e => e.currentTarget.style.background = 'rgba(99,102,241,0.12)'}
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" /></svg>
                  {i.clean_select}
                  <input ref={cleanFileInputRef} type="file" multiple className="hidden" onChange={(e) => { const f = Array.from(e.target.files); if (!session) { storeFilesForAfterAuth(f); router.push('/dashboard?mode=clean'); return }; setCleanFiles(prev => [...prev, ...f]); setCleanDone(false) }} />
                </label>
              </>
            ) : (
              <>
                <div className="flex flex-wrap gap-2 justify-center mb-8 max-h-36 overflow-y-auto">
                  {cleanFiles.map((f, idx) => (
                    <div key={idx} className="flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs" style={{background: 'rgba(99,102,241,0.06)', border: '1px solid rgba(99,102,241,0.15)'}}>
                      <IconFile />
                      <span className="text-gray-300 max-w-[120px] truncate">{f.name}</span>
                      <span className="text-gray-600">{(f.size/1024).toFixed(0)}kb</span>
                    </div>
                  ))}
                </div>
                <div className="flex items-center justify-center gap-3 flex-wrap">
                  <button onClick={processCleanHome} disabled={cleanProcessing} className="inline-flex items-center gap-2.5 px-7 sm:px-9 py-3.5 rounded-xl text-sm font-semibold text-white disabled:opacity-40 transition-all duration-200" style={{background: 'linear-gradient(135deg, #4f46e5, #6366f1)', boxShadow: '0 0 20px rgba(99,102,241,0.3)'}}>
                    {cleanProcessing ? <><IconSpin />{i.clean_processing}</> : <><IconDownload />{i.clean_process}</>}
                  </button>
                  <button onClick={() => { setCleanFiles([]); setCleanDone(false) }} className="px-4 py-3.5 text-xs text-gray-500 hover:text-gray-300 transition-colors tracking-wide">{i.clear}</button>
                </div>
                {cleanDone && (
                  <div className="mt-6 inline-flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-medium" style={{background: 'rgba(34,197,94,0.08)', border: '1px solid rgba(34,197,94,0.18)', color: '#86efac'}}>
                    <IconCheck />{i.clean_success(cleanFiles.length)}
                  </div>
                )}
              </>
            )}
          </div>
          )}
        </Reveal>

        {/* Stats */}
        <Reveal>
          <p className="text-center text-[11px] text-gray-600 mb-20 sm:mb-24 tracking-wide">{i.stats}</p>
        </Reveal>

        {/* Feature cards */}
        <div id="features" className="mb-20 sm:mb-28">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
            {features.map(({ Icon, title, desc, sub, accent, href }, idx) => (
              <Reveal key={idx} delay={idx * 90} className="flex flex-col">
                <div
                  className="rounded-2xl p-6 sm:p-7 flex flex-col flex-1 transition-all duration-300 hover:scale-[1.02]"
                  onMouseMove={(e) => {
                    const rect = e.currentTarget.getBoundingClientRect()
                    const x = ((e.clientX - rect.left) / rect.width * 100).toFixed(1)
                    const y = ((e.clientY - rect.top) / rect.height * 100).toFixed(1)
                    e.currentTarget.style.background = `radial-gradient(circle at ${x}% ${y}%, ${accent}12 0%, rgba(255,255,255,0.02) 65%)`
                    e.currentTarget.style.borderColor = `${accent}40`
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.background = 'rgba(255,255,255,0.02)'
                    e.currentTarget.style.borderColor = 'rgba(255,255,255,0.06)'
                  }}
                  style={{background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.06)'}}
                >
                  <div className="w-11 h-11 rounded-2xl flex items-center justify-center mb-5" style={{background: `${accent}15`, color: accent}}>
                    <Icon />
                  </div>
                  <p className="font-bold text-[16px] text-white mb-3 tracking-tight">{title}</p>
                  <p className="text-gray-400 text-[13px] leading-relaxed mb-4">{desc}</p>
                  <div className="px-3 py-2 rounded-lg mb-5" style={{background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.05)'}}>
                    <p className="text-[11px] tracking-wide font-medium" style={{color: accent}}>{sub}</p>
                  </div>
                  <div className="mt-auto">
                    <Link href={href} className="text-[12px] font-medium transition-colors hover:opacity-80" style={{color: accent}}>
                      {i.know_more}
                    </Link>
                  </div>
                </div>
              </Reveal>
            ))}
          </div>

          {/* AI features — coming soon */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {[
              { Icon: IconAIExpand, title: i.ai_outpaint_title, desc: i.ai_outpaint_desc, sub: i.ai_outpaint_tag, accent: '#8b5cf6' },
              { Icon: IconAIText,   title: i.ai_copy_title,     desc: i.ai_copy_desc,     sub: i.ai_copy_tag,     accent: '#6366f1' },
            ].map(({ Icon, title, desc, sub, accent }, idx) => (
              <Reveal key={idx} delay={idx * 90} className="flex flex-col">
                <div
                  className="relative rounded-2xl p-6 sm:p-7 flex flex-col flex-1 overflow-hidden"
                  style={{background: 'rgba(255,255,255,0.015)', border: `1px solid ${accent}25`}}
                >
                  <div className="absolute top-4 right-4 px-2 py-0.5 rounded-full text-[10px] font-semibold uppercase tracking-wider"
                    style={{background: `${accent}18`, border: `1px solid ${accent}40`, color: accent}}>
                    {i.ai_section_label}
                  </div>
                  <div className="w-11 h-11 rounded-2xl flex items-center justify-center mb-5" style={{background: `${accent}12`, color: accent, opacity: 0.75}}>
                    <Icon />
                  </div>
                  <p className="font-bold text-[16px] mb-3 tracking-tight" style={{color: 'rgba(255,255,255,0.55)'}}>{title}</p>
                  <p className="text-gray-600 text-[13px] leading-relaxed mb-4">{desc}</p>
                  <div className="px-3 py-2 rounded-lg mt-auto" style={{background: 'rgba(255,255,255,0.025)', border: `1px solid ${accent}18`}}>
                    <p className="text-[11px] tracking-wide font-medium" style={{color: `${accent}88`}}>{sub}</p>
                  </div>
                </div>
              </Reveal>
            ))}
          </div>
        </div>

        {/* ─── AI Coming Soon ─── */}
        <div id="ai" className="mb-20 sm:mb-28">
          <Reveal>
            <div className="flex flex-col items-center text-center mb-10 sm:mb-12">
              {/* Badge */}
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full mb-5 text-[11px] font-semibold uppercase tracking-widest"
                style={{background: 'linear-gradient(135deg, rgba(99,102,241,0.15), rgba(139,92,246,0.15))', border: '1px solid rgba(139,92,246,0.3)', color: '#c4b5fd'}}>
                <span className="w-1.5 h-1.5 rounded-full bg-violet-400 animate-pulse" />
                {i.ai_section_label}
              </div>
              <h2 className="text-2xl sm:text-3xl font-bold tracking-tight mb-4"
                style={{background: 'linear-gradient(135deg, #e0e7ff, #a5b4fc, #c084fc)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text'}}>
                {i.ai_section_title}
              </h2>
              <p className="text-gray-400 text-[14px] max-w-md leading-relaxed">{i.ai_section_sub}</p>
            </div>
          </Reveal>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 mb-10">

            {/* AI Outpainting */}
            <Reveal delay={0}>
              <div
                className="relative rounded-2xl p-7 h-full flex flex-col overflow-hidden group"
                style={{background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(139,92,246,0.18)', transition: 'border-color 0.3s ease, box-shadow 0.3s ease'}}
                onMouseEnter={e => { e.currentTarget.style.borderColor = 'rgba(139,92,246,0.45)'; e.currentTarget.style.boxShadow = '0 0 40px rgba(139,92,246,0.12)' }}
                onMouseLeave={e => { e.currentTarget.style.borderColor = 'rgba(139,92,246,0.18)'; e.currentTarget.style.boxShadow = 'none' }}
              >
                {/* Ambient glow */}
                <div className="absolute inset-0 pointer-events-none" style={{background: 'radial-gradient(ellipse at 20% 0%, rgba(139,92,246,0.08) 0%, transparent 60%)'}} />

                {/* Icon */}
                <div className="relative w-12 h-12 rounded-2xl flex items-center justify-center mb-5 shrink-0"
                  style={{background: 'linear-gradient(135deg, rgba(99,102,241,0.2), rgba(139,92,246,0.2))', border: '1px solid rgba(139,92,246,0.3)'}}>
                  <svg className="w-6 h-6" fill="none" stroke="url(#grad-outpaint)" strokeWidth={1.5} viewBox="0 0 24 24">
                    <defs>
                      <linearGradient id="grad-outpaint" x1="0" y1="0" x2="1" y2="1">
                        <stop offset="0%" stopColor="#a5b4fc"/>
                        <stop offset="100%" stopColor="#c084fc"/>
                      </linearGradient>
                    </defs>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 3.75v4.5m0-4.5h4.5m-4.5 0L9 9M3.75 20.25v-4.5m0 4.5h4.5m-4.5 0L9 15M20.25 3.75h-4.5m4.5 0v4.5m0-4.5L15 9m5.25 11.25h-4.5m4.5 0v-4.5m0 4.5L15 15" />
                  </svg>
                </div>

                <p className="relative text-white font-bold text-[17px] tracking-tight mb-2">{i.ai_outpaint_title}</p>
                <p className="relative text-gray-400 text-[13px] leading-relaxed mb-5">{i.ai_outpaint_desc}</p>

                {/* Visual demo mockup */}
                <div className="relative rounded-xl overflow-hidden mb-5" style={{background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', height: 80}}>
                  <div className="absolute inset-0 flex items-center justify-center gap-0">
                    {/* Simulated: narrow original → wide expanded */}
                    <div className="h-full flex items-center justify-center" style={{width: '38%', background: 'rgba(99,102,241,0.12)', borderRight: '2px dashed rgba(139,92,246,0.4)'}}>
                      <span className="text-[10px] text-indigo-300/60 font-medium">original</span>
                    </div>
                    <div className="h-full flex-1 flex items-center justify-center" style={{background: 'linear-gradient(90deg, rgba(139,92,246,0.07), rgba(99,102,241,0.04))'}}>
                      <span className="text-[10px] text-violet-400/50 font-medium tracking-wide">ai expanded</span>
                    </div>
                  </div>
                  {/* Expand arrows */}
                  <div className="absolute inset-0 flex items-center justify-start pl-1 pointer-events-none">
                    <svg className="w-4 h-4 text-violet-500/40" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 19l-7-7 7-7M18 19l-7-7 7-7" /></svg>
                  </div>
                  <div className="absolute inset-0 flex items-center justify-end pr-1 pointer-events-none">
                    <svg className="w-4 h-4 text-violet-500/40" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 5l7 7-7 7M6 5l7 7-7 7" /></svg>
                  </div>
                </div>

                <div className="relative mt-auto">
                  <div className="px-3 py-2 rounded-lg" style={{background: 'rgba(139,92,246,0.07)', border: '1px solid rgba(139,92,246,0.2)'}}>
                    <p className="text-[11px] font-medium tracking-wide" style={{color: '#c084fc'}}>{i.ai_outpaint_tag}</p>
                  </div>
                </div>
              </div>
            </Reveal>

            {/* Auto Ad Copy */}
            <Reveal delay={90}>
              <div
                className="relative rounded-2xl p-7 h-full flex flex-col overflow-hidden"
                style={{background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(99,102,241,0.18)', transition: 'border-color 0.3s ease, box-shadow 0.3s ease'}}
                onMouseEnter={e => { e.currentTarget.style.borderColor = 'rgba(99,102,241,0.45)'; e.currentTarget.style.boxShadow = '0 0 40px rgba(99,102,241,0.12)' }}
                onMouseLeave={e => { e.currentTarget.style.borderColor = 'rgba(99,102,241,0.18)'; e.currentTarget.style.boxShadow = 'none' }}
              >
                {/* Ambient glow */}
                <div className="absolute inset-0 pointer-events-none" style={{background: 'radial-gradient(ellipse at 80% 0%, rgba(99,102,241,0.08) 0%, transparent 60%)'}} />

                {/* Icon */}
                <div className="relative w-12 h-12 rounded-2xl flex items-center justify-center mb-5 shrink-0"
                  style={{background: 'linear-gradient(135deg, rgba(37,99,235,0.2), rgba(99,102,241,0.2))', border: '1px solid rgba(99,102,241,0.3)'}}>
                  <svg className="w-6 h-6" fill="none" strokeWidth={1.5} viewBox="0 0 24 24">
                    <defs>
                      <linearGradient id="grad-copy" x1="0" y1="0" x2="1" y2="1">
                        <stop offset="0%" stopColor="#93c5fd"/>
                        <stop offset="100%" stopColor="#a5b4fc"/>
                      </linearGradient>
                    </defs>
                    <path stroke="url(#grad-copy)" strokeLinecap="round" strokeLinejoin="round" d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 01.865-.501 48.172 48.172 0 003.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0012 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018z" />
                  </svg>
                </div>

                <p className="relative text-white font-bold text-[17px] tracking-tight mb-2">{i.ai_copy_title}</p>
                <p className="relative text-gray-400 text-[13px] leading-relaxed mb-5">{i.ai_copy_desc}</p>

                {/* Visual demo mockup — fake generated copy lines */}
                <div className="relative rounded-xl p-3.5 mb-5 space-y-2.5" style={{background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)'}}>
                  {[
                    { platform: 'Meta', color: '#1877f2', line1: '90%', line2: '60%' },
                    { platform: 'TikTok', color: '#ff0050', line1: '75%', line2: '45%' },
                  ].map(({ platform, color, line1, line2 }) => (
                    <div key={platform} className="flex items-start gap-2.5">
                      <div className="w-1.5 h-1.5 rounded-full mt-1.5 shrink-0" style={{background: color}} />
                      <div className="flex-1 space-y-1">
                        <div className="h-2 rounded-full" style={{width: line1, background: 'rgba(255,255,255,0.08)'}} />
                        <div className="h-2 rounded-full" style={{width: line2, background: 'rgba(255,255,255,0.05)'}} />
                      </div>
                      <span className="text-[9px] font-medium shrink-0 mt-0.5" style={{color: `${color}99`}}>{platform}</span>
                    </div>
                  ))}
                  {/* Blinking cursor */}
                  <div className="flex items-center gap-1.5">
                    <div className="w-1.5 h-1.5 rounded-full shrink-0" style={{background: '#4285f4'}} />
                    <div className="h-2 rounded-full" style={{width: '30%', background: 'rgba(255,255,255,0.06)'}} />
                    <div className="w-0.5 h-3 rounded-full bg-indigo-400 animate-pulse" />
                  </div>
                </div>

                <div className="relative mt-auto">
                  <div className="px-3 py-2 rounded-lg" style={{background: 'rgba(99,102,241,0.07)', border: '1px solid rgba(99,102,241,0.2)'}}>
                    <p className="text-[11px] font-medium tracking-wide" style={{color: '#a5b4fc'}}>{i.ai_copy_tag}</p>
                  </div>
                </div>
              </div>
            </Reveal>
          </div>

          {/* Waitlist CTA */}
          <Reveal delay={120}>
            <div className="flex flex-col sm:flex-row items-center justify-between gap-5 px-6 py-5 rounded-2xl"
              style={{background: 'linear-gradient(135deg, rgba(99,102,241,0.07), rgba(139,92,246,0.07))', border: '1px solid rgba(139,92,246,0.2)'}}>
              <div>
                <p className="text-white font-semibold text-[14px] mb-0.5">{i.ai_waitlist_note}</p>
                <p className="text-gray-500 text-[12px]">Early access · Priority onboarding · Founding price locked in.</p>
              </div>
              <a
                href="mailto:hello@metaclean.pro?subject=AI%20Waitlist"
                onMouseEnter={e => { e.currentTarget.style.backgroundPosition = '100% 50%'; e.currentTarget.style.boxShadow = '0 0 0 1px rgba(139,92,246,0.6), 0 0 20px rgba(99,102,241,0.4), 0 0 45px rgba(139,92,246,0.2)' }}
                onMouseLeave={e => { e.currentTarget.style.backgroundPosition = '0% 50%'; e.currentTarget.style.boxShadow = 'none' }}
                onMouseMove={e => { const rect = e.currentTarget.getBoundingClientRect(); e.currentTarget.style.backgroundPosition = `${((e.clientX - rect.left) / rect.width * 100).toFixed(1)}% 50%` }}
                className="shrink-0 inline-flex items-center gap-2 px-6 py-2.5 rounded-xl text-[13px] font-semibold text-white whitespace-nowrap"
                style={{background: 'linear-gradient(135deg, #2563eb, #4f46e5, #8b5cf6, #6366f1)', backgroundSize: '300% 300%', backgroundPosition: '0% 50%', transition: 'box-shadow 0.3s ease, background-position 0.1s ease'}}
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                </svg>
                {i.ai_waitlist_cta}
              </a>
            </div>
          </Reveal>
        </div>

        {/* Pricing */}
        <div id="pricing">
          <Reveal>
            <p className="text-center text-[11px] text-gray-500 uppercase tracking-widest mb-3 font-medium">Pricing</p>
            <h2 className="text-center text-2xl sm:text-3xl font-bold tracking-tight mb-10 sm:mb-12">Simple, transparent pricing</h2>
          </Reveal>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 max-w-3xl mx-auto">
            <Reveal delay={0} className="flex flex-col">
              <div
                className="rounded-2xl p-6 sm:p-7 flex flex-col flex-1 transition-all duration-300"
                onMouseMove={(e) => {
                  const r = e.currentTarget.getBoundingClientRect()
                  const x = ((e.clientX - r.left) / r.width * 100).toFixed(1)
                  const y = ((e.clientY - r.top) / r.height * 100).toFixed(1)
                  e.currentTarget.style.background = `radial-gradient(circle at ${x}% ${y}%, rgba(255,255,255,0.045) 0%, rgba(255,255,255,0.02) 65%)`
                  e.currentTarget.style.borderColor = 'rgba(255,255,255,0.12)'
                  e.currentTarget.style.transform = 'translateY(-2px)'
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.background = 'rgba(255,255,255,0.02)'
                  e.currentTarget.style.borderColor = 'rgba(255,255,255,0.07)'
                  e.currentTarget.style.transform = 'none'
                }}
                style={{background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.07)'}}
              >
                <p className="text-[11px] text-gray-500 uppercase tracking-widest font-medium mb-4">{i.free}</p>
                <div className="flex items-baseline gap-1 mb-1">
                  <span className="text-4xl font-bold">€0</span>
                  <span className="text-gray-500 text-sm">/mo</span>
                </div>
                <p className="text-gray-500 text-[13px] mb-6">{i.free_desc}</p>
                <div className="mt-auto">
                  <Link href="/login" className="block w-full py-2.5 rounded-xl text-[13px] font-medium text-center text-gray-300 transition-colors hover:text-white" style={{border: '1px solid rgba(255,255,255,0.1)'}}>
                    {i.free_sub}
                  </Link>
                </div>
              </div>
            </Reveal>

            <Reveal delay={100} className="flex flex-col">
              <div
                className="rounded-2xl p-6 sm:p-7 relative overflow-hidden flex flex-col flex-1 transition-all duration-300"
                style={{background: 'linear-gradient(145deg, rgba(37,99,235,0.15), rgba(79,70,229,0.2))', border: '1px solid rgba(99,102,241,0.35)', boxShadow: '0 0 40px rgba(79,70,229,0.1)'}}
                onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-2px)'; e.currentTarget.style.boxShadow = '0 0 60px rgba(79,70,229,0.2), 0 8px 20px rgba(0,0,0,0.2)' }}
                onMouseLeave={e => { e.currentTarget.style.transform = 'none'; e.currentTarget.style.boxShadow = '0 0 40px rgba(79,70,229,0.1)' }}
              >
                <div className="absolute top-0 right-0 left-0 h-px" style={{background: 'linear-gradient(90deg, transparent, rgba(99,102,241,0.6), transparent)'}} />
                <p className="text-[11px] uppercase tracking-widest font-medium mb-4" style={{color: '#818cf8'}}>{i.pro_sub}</p>
                <div className="flex items-baseline gap-1 mb-1">
                  <span className="text-4xl font-bold">€9</span>
                  <span className="text-gray-400 text-sm">/mo</span>
                </div>
                <p className="text-gray-300 text-[13px] mb-6">{i.pro_desc}</p>
                <div className="mt-auto">
                  <Link href="/login" {...glowHandlers} className="block w-full py-2.5 rounded-xl text-[13px] font-semibold text-center text-white" style={glowStyle}>
                    {i.nav_cta}
                  </Link>
                </div>
              </div>
            </Reveal>

            <Reveal delay={200} className="flex flex-col">
              <div
                className="rounded-2xl p-6 sm:p-7 relative overflow-hidden flex flex-col flex-1 transition-all duration-300"
                style={{background: 'rgba(255,255,255,0.015)', border: '1px solid rgba(139,92,246,0.22)'}}
                onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-2px)'; e.currentTarget.style.borderColor = 'rgba(139,92,246,0.45)'; e.currentTarget.style.boxShadow = '0 0 40px rgba(139,92,246,0.1)' }}
                onMouseLeave={e => { e.currentTarget.style.transform = 'none'; e.currentTarget.style.borderColor = 'rgba(139,92,246,0.22)'; e.currentTarget.style.boxShadow = 'none' }}
              >
                <div className="absolute inset-0 pointer-events-none" style={{background: 'radial-gradient(ellipse at 50% 0%, rgba(139,92,246,0.07) 0%, transparent 65%)'}} />
                <div className="flex items-center gap-2 mb-4">
                  <p className="text-[11px] uppercase tracking-widest font-medium" style={{color: '#c084fc'}}>{i.ai_plan}</p>
                  <span className="px-1.5 py-0.5 rounded-full text-[9px] font-semibold uppercase tracking-wider" style={{background: 'rgba(192,132,252,0.12)', border: '1px solid rgba(192,132,252,0.3)', color: '#c084fc'}}>{i.ai_plan_sub}</span>
                </div>
                <div className="flex items-baseline gap-1 mb-1">
                  <span className="text-4xl font-bold" style={{color: 'rgba(255,255,255,0.3)'}}>€?</span>
                  <span className="text-gray-600 text-sm">/mo</span>
                </div>
                <p className="text-gray-600 text-[13px] mb-6">{i.ai_plan_desc}</p>
                <div className="mt-auto">
                  <a
                    href="mailto:hello@metaclean.pro?subject=AI%20Waitlist"
                    className="block w-full py-2.5 rounded-xl text-[13px] font-medium text-center transition-colors"
                    style={{border: '1px solid rgba(139,92,246,0.3)', color: '#c084fc', background: 'rgba(139,92,246,0.07)'}}
                    onMouseEnter={e => { e.currentTarget.style.background = 'rgba(139,92,246,0.14)'; e.currentTarget.style.borderColor = 'rgba(139,92,246,0.5)' }}
                    onMouseLeave={e => { e.currentTarget.style.background = 'rgba(139,92,246,0.07)'; e.currentTarget.style.borderColor = 'rgba(139,92,246,0.3)' }}
                  >
                    {i.ai_waitlist_cta}
                  </a>
                </div>
              </div>
            </Reveal>
          </div>
        </div>


      </div>

      {/* Footer */}
      <footer className="relative z-10 border-t border-white/5 px-4 sm:px-8 py-6 flex flex-col sm:flex-row items-center justify-between gap-3 sm:gap-0">
        <Logo />
        <div className="flex items-center gap-5 text-[12px] text-gray-500">
          <Link href="/features" className="hover:text-gray-300 transition-colors">Features</Link>
          <Link href="/pricing" className="hover:text-gray-300 transition-colors">Pricing</Link>
          <Link href="/privacy" className="hover:text-gray-300 transition-colors">Privacy</Link>
          <Link href="/terms" className="hover:text-gray-300 transition-colors">Terms</Link>
          <span>© {new Date().getFullYear()} MetaClean</span>
        </div>
        <div className="flex items-center gap-2">
          <a href="https://github.com/FranciscoSilvaPT" target="_blank" rel="noopener noreferrer" className="flex items-center justify-center w-8 h-8 rounded-lg text-gray-500 hover:text-white transition-colors" style={{background:'rgba(255,255,255,0.04)',border:'1px solid rgba(255,255,255,0.07)'}}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><path d="M12 0C5.374 0 0 5.373 0 12c0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23A11.509 11.509 0 0112 5.803c1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576C20.566 21.797 24 17.3 24 12c0-6.627-5.373-12-12-12z"/></svg>
          </a>
          <a href="https://www.linkedin.com/in/francisco-silva-59747619b/" target="_blank" rel="noopener noreferrer" className="flex items-center justify-center w-8 h-8 rounded-lg text-gray-500 transition-colors" style={{background:'rgba(255,255,255,0.04)',border:'1px solid rgba(255,255,255,0.07)'}} onMouseEnter={e=>{e.currentTarget.style.color='#60a5fa';e.currentTarget.style.background='rgba(10,102,194,0.08)';e.currentTarget.style.borderColor='rgba(10,102,194,0.25)'}} onMouseLeave={e=>{e.currentTarget.style.color='';e.currentTarget.style.background='rgba(255,255,255,0.04)';e.currentTarget.style.borderColor='rgba(255,255,255,0.07)'}}>
            <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>
          </a>
        </div>
      </footer>
    </main>
  )
}
